### ISSUE TITLE
fof_install.php throwing errors due to ' around field names when adding columns/keys

### ISSUE THREAD

**Issue by pperrin** [RomanSixty/Feed-on-Feeds#26] opened 2015-03-31 15:51 UTC
I have fixed these to get my install to work - but don't have the resource to check if this is a generic issue or just with my version of mysql...

Single quotes seem to be needed when checking for the existence of the fields, but not in the sql to add them if missing.

**Comment by RomanSixty** [comment] 2018-12-01 16:55
Closing because the issue is rather old, I can't reproduce the problem and the file in question has been modified a few times since then.

**Closed by RomanSixty** 2018-12-01 16:55 UTC
